name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    # container: jekyll/jekyll

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Test web site changes
      run: ./script/cibuild